### ISSUE TITLE
Mapear o site

### ISSUE THREAD

**Issue by ArthurGarcia2** [ArthurGarcia2/projeto_ong_olaria#1]
**Criar um mapa mental**

-Tem de ser com cores claras
-Com letras visíveis
-De fácil entendimento

**Comment by TaMecLek** [comment]
UwU

**Comment by TaMecLek** [comment]
-segui os requisitos e criei um layout 
![tabela](https://user-images.githubusercontent.com/61690263/113064180-e5b18f00-918c-11eb-93b8-2fe4e8ad631b.jpg)
