### ISSUE TITLE
Criar um Layout básico

### ISSUE THREAD

**Issue by ArthurGarcia2** [ArthurGarcia2/projeto_ong_olaria#3]
Criar um Layout básico do site, será usado como gabarito a ser seguido

**Comment by TaMecLek** [comment]
Layout básico pensado:
![WhatsApp Image 2021-04-07 at 22 29 11 (1)](https://user-images.githubusercontent.com/61690263/115097048-56cba300-9efe-11eb-99d3-1bd105f7a28e.jpeg)
![WhatsApp Image 2021-04-07 at 22 29 11 (2)](https://user-images.githubusercontent.com/61690263/115097050-57643980-9efe-11eb-938c-27747a9f9451.jpeg)
![WhatsApp Image 2021-04-07 at 22 29 11 (3)](https://user-images.githubusercontent.com/61690263/115097051-57fcd000-9efe-11eb-9954-7d8a10d53be8.jpeg)
![WhatsApp Image 2021-04-07 at 22 29 11 (4)](https://user-images.githubusercontent.com/61690263/115097052-57fcd000-9efe-11eb-87ed-9691a98eab1e.jpeg)
![WhatsApp Image 2021-04-07 at 22 29 11 (5)](https://user-images.githubusercontent.com/61690263/115097053-58956680-9efe-11eb-9b7b-1e173be667de.jpeg)
![WhatsApp Image 2021-04-07 at 22 29 11 (6)](https://user-images.githubusercontent.com/61690263/115097054-58956680-9efe-11eb-9024-5fd027a8e533.jpeg)
![WhatsApp Image 2021-04-07 at 22 29 11](https://user-images.githubusercontent.com/61690263/115097055-592dfd00-9efe-11eb-84f7-a877b1cee021.jpeg)

Em PDF:
[paginas ong.pdf](https://github.com/ArthurGarcia2/projeto_ong_olaria/files/6328413/paginas.ong.pdf)
